const express = require('express')
const config = require('../../configs/configs')

const HTTPCodes = config.HTTPCode
const admin_router = express.Router()
const { connect_db } = require('../../configs/db')

admin_router.get('/userlist', (req, res) => {
    // Check identity:
    if (!req.session.isAdmin) {
        res.status(HTTPCodes.Unauthorized).json({
            status: 'fail',
            data: {
                error_code: config.ErrorCodes.NotAdmin,
            },
            message: 'Blocking list can only be generated by the admin',
        })
        return
    }
    // Send user list
    const query = 'SELECT email FROM Account'
    connect_db()
        .then((database) => {
            return database.query(query)
        })
        .then((db_result) => {
            res.status(HTTPCodes.Ok).json({
                status: 'success',
                data: {
                    email_list: db_result.rows,
                },
                message: '[INFO] Generated User information',
            })
        })
})

module.exports = admin_router
