const express = require('express')
const config = require('../../configs/configs')
const utils = require('../../util/utils')
const { connect_db } = require('../../configs/db')

const HTTPCodes = config.HTTPCode
const block_router = express.Router()

block_router.get('/', (req, res) => {
    // Check identity:
    if (!req.session.isAdmin) {
        res.status(HTTPCodes.Unauthorized).json({
            status: 'fail',
            data: {
                error_code: config.ErrorCodes.NotAdmin,
            },
            message: 'Blocking list can only be generated by the admin',
        })
        return
    }
    // Send blocking list
    const query =
        'SELECT A.email,B.start_at AS startAt,B.end_at AS endAt\
                    FROM Account A, Block B\
                    WHERE A.user_id = B.user_id'
    connect_db()
        .then((database) => database.query(query))
        .then((db_result) => {
            console.log(db_result)
            const blocking_list = db_result.rows.map((row) => {
                return {
                    email: row.email,
                    startAt: utils.format_date(row.startat),
                    endAt: utils.format_date(row.endat),
                }
            })

            res.status(HTTPCodes.Ok).json({
                status: 'sucess',
                data: {
                    block_list: blocking_list,
                },
                message: '[INFO] Blocking list generated',
            })
            console.log(db_result)
        })
        .catch((err) => {
            console.error(
                `[Error] Failed to send blocking list.\n Error: ${err}`
            )
            res.status(HTTPCodes.BadRequest).json({
                status: 'error',
                message: '[Error] Invalid query format',
            })
        })
})

module.exports = block_router
